<template>
  <aside class="sidebar-shell">
    <section v-if="viewMode === 'mode-picker'" class="sidebar-panel mode-panel">
      <div class="panel-head">
        <div class="section-label">创作模式</div>
        <h2 class="panel-title">选择一个写作入口</h2>
        <p class="panel-subtitle">点击任意模式后，左侧会切换到该模式专属的历史会话页。</p>
      </div>

      <div class="ability-list">
        <button
          v-for="ability in abilities"
          :key="ability.key"
          type="button"
          :class="['ability-card', { active: activeModeKey === ability.key }]"
          @click="$emit('select-ability', ability.key)"
        >
          <div class="ability-index">{{ ability.index }}</div>
          <div class="ability-copy">
            <div class="ability-title">{{ ability.title }}</div>
            <div class="ability-subtitle">{{ ability.subtitle }}</div>
            <p class="ability-description">{{ ability.description }}</p>
          </div>
        </button>
      </div>
    </section>

    <section v-else class="sidebar-panel session-panel">
      <div class="session-toolbar">
        <button
          type="button"
          class="toolbar-button"
          @click="$emit('back-to-modes')"
        >
          返回
        </button>

        <div class="toolbar-copy">
          <div class="section-label">历史会话</div>
          <div class="toolbar-title">{{ currentAbility.title }}</div>
          <div class="toolbar-subtitle">{{ currentAbility.subtitle }}</div>
        </div>

        <button
          type="button"
          class="toolbar-button primary"
          @click="$emit('create-session', currentAbility.key)"
        >
          新建会话
        </button>
      </div>

      <div class="session-list">
        <div v-if="loading" class="session-empty">正在加载会话列表...</div>

        <div v-else-if="!sessions.length" class="session-empty">
          <div class="session-empty-title">当前模式还没有历史会话</div>
          <div class="session-empty-copy">点击右上角“新建会话”即可开始。</div>
        </div>

        <article
          v-for="session in sessions"
          :key="session.chatId"
          :class="['session-item', { selected: session.chatId === selectedSessionId }]"
        >
          <button
            type="button"
            class="session-main"
            @click="$emit('select-session', { mode: currentAbility.key, chatId: session.chatId })"
          >
            <div class="session-title-row">
              <div class="session-name">{{ session.title }}</div>
              <span v-if="session.userRenamed" class="session-badge">手动</span>
              <span v-else-if="session.autoGeneratedTitle" class="session-badge auto">自动</span>
            </div>

            <div class="session-preview">
              {{ session.preview || '完成首轮问答后会自动生成标题和摘要。' }}
            </div>

            <div class="session-meta">
              <span>{{ formatTime(session.updatedAt) }}</span>
              <span class="session-id">{{ session.chatId }}</span>
            </div>
          </button>

          <div class="session-actions">
            <button
              type="button"
              class="session-action"
              @click.stop="openRenameDialog(session)"
            >
              重命名
            </button>
            <button
              type="button"
              class="session-action danger"
              @click.stop="$emit('delete-session', session)"
            >
              删除
            </button>
          </div>
        </article>
      </div>

      <div
        v-if="renameTargetSession"
        class="rename-dialog-backdrop"
        @click.self="closeRenameDialog"
      >
        <div class="rename-dialog">
          <div class="rename-dialog-label">重命名会话</div>
          <div class="rename-dialog-title">{{ renameTargetSession.title }}</div>

          <form class="rename-form" @submit.prevent="submitRename">
            <input
              ref="renameInputRef"
              v-model="renameDraft"
              class="rename-input"
              maxlength="20"
              autocomplete="off"
            >

            <div class="rename-dialog-actions">
              <button type="submit" class="rename-action primary">保存</button>
              <button type="button" class="rename-action" @click="closeRenameDialog">取消</button>
            </div>
          </form>
        </div>
      </div>
    </section>
  </aside>
</template>

<script setup>
import { computed, nextTick, ref } from 'vue'

const props = defineProps({
  viewMode: {
    type: String,
    default: 'mode-picker'
  },
  abilities: {
    type: Array,
    default: () => []
  },
  activeModeKey: {
    type: String,
    default: ''
  },
  sessions: {
    type: Array,
    default: () => []
  },
  selectedSessionId: {
    type: String,
    default: ''
  },
  loading: {
    type: Boolean,
    default: false
  }
})

const emit = defineEmits([
  'select-ability',
  'back-to-modes',
  'create-session',
  'select-session',
  'rename-session',
  'delete-session'
])

const renameInputRef = ref(null)
const renameTargetSession = ref(null)
const renameDraft = ref('')

const currentAbility = computed(() => {
  return props.abilities.find((ability) => ability.key === props.activeModeKey) ?? props.abilities[0] ?? {}
})

const formatTime = (value) => {
  if (!value) {
    return '刚刚'
  }

  const date = new Date(value)
  if (Number.isNaN(date.getTime())) {
    return '刚刚'
  }

  return date.toLocaleString('zh-CN', {
    month: '2-digit',
    day: '2-digit',
    hour: '2-digit',
    minute: '2-digit'
  })
}

const openRenameDialog = async (session) => {
  renameTargetSession.value = session
  renameDraft.value = session.title
  await nextTick()
  renameInputRef.value?.focus()
  renameInputRef.value?.select()
}

const closeRenameDialog = () => {
  renameTargetSession.value = null
  renameDraft.value = ''
}

const submitRename = () => {
  const session = renameTargetSession.value
  const title = renameDraft.value.trim()

  if (!session) {
    return
  }

  if (!title || title === session.title) {
    closeRenameDialog()
    return
  }

  closeRenameDialog()
  emit('rename-session', {
    chatId: session.chatId,
    title
  })
}
</script>

<style scoped>
.sidebar-shell {
  min-height: 0;
  height: 100%;
}

.sidebar-panel {
  min-height: 0;
  height: 100%;
  display: flex;
  flex-direction: column;
  border-radius: 28px;
  border: 1px solid rgba(123, 184, 255, 0.14);
  background: rgba(8, 16, 32, 0.82);
  box-shadow:
    0 24px 70px rgba(0, 10, 30, 0.36),
    inset 0 0 0 1px rgba(255, 255, 255, 0.03);
}

.mode-panel {
  padding: 20px;
}

.panel-head {
  flex: 0 0 auto;
  margin-bottom: 18px;
}

.section-label {
  color: #8ec9ff;
  font-size: 12px;
  letter-spacing: 0.18em;
  text-transform: uppercase;
}

.panel-title {
  margin: 10px 0 0;
  font-size: 1.35rem;
}

.panel-subtitle {
  margin: 10px 0 0;
  color: rgba(214, 231, 255, 0.68);
  line-height: 1.72;
  font-size: 13px;
}

.ability-list {
  min-height: 0;
  display: flex;
  flex: 1;
  flex-direction: column;
  gap: 12px;
}

.ability-card {
  width: 100%;
  display: grid;
  grid-template-columns: 52px 1fr;
  gap: 14px;
  padding: 16px;
  border: 1px solid rgba(123, 184, 255, 0.12);
  border-radius: 22px;
  background: rgba(10, 20, 40, 0.72);
  color: inherit;
  cursor: pointer;
  text-align: left;
  transition: transform 0.2s ease, border-color 0.2s ease, background 0.2s ease;
}

.ability-card:hover {
  transform: translateY(-1px);
  border-color: rgba(125, 202, 255, 0.26);
}

.ability-card.active {
  border-color: rgba(81, 178, 255, 0.42);
  background: linear-gradient(180deg, rgba(14, 35, 67, 0.94), rgba(8, 21, 43, 0.92));
  box-shadow: 0 18px 36px rgba(22, 79, 170, 0.22);
}

.ability-index {
  width: 52px;
  height: 52px;
  border-radius: 16px;
  display: flex;
  align-items: center;
  justify-content: center;
  background: linear-gradient(135deg, rgba(32, 121, 255, 0.92), rgba(57, 211, 255, 0.86));
  color: #fff;
  font-size: 1.15rem;
  font-weight: 700;
}

.ability-title {
  font-size: 1.05rem;
  font-weight: 700;
}

.ability-subtitle {
  margin-top: 4px;
  color: #8ecbff;
  font-size: 12px;
  letter-spacing: 0.14em;
  text-transform: uppercase;
}

.ability-description {
  margin: 10px 0 0;
  color: rgba(214, 231, 255, 0.68);
  line-height: 1.72;
  font-size: 13px;
}

.session-panel {
  position: relative;
  padding: 18px;
}

.session-toolbar {
  flex: 0 0 auto;
  display: grid;
  grid-template-columns: auto minmax(0, 1fr) auto;
  gap: 12px;
  align-items: center;
  margin-bottom: 16px;
}

.toolbar-copy {
  min-width: 0;
}

.toolbar-title {
  margin-top: 6px;
  font-size: 1.1rem;
  font-weight: 700;
  color: #eef7ff;
}

.toolbar-subtitle {
  margin-top: 4px;
  color: rgba(201, 224, 255, 0.56);
  font-size: 12px;
  letter-spacing: 0.12em;
  text-transform: uppercase;
}

.toolbar-button {
  height: 38px;
  padding: 0 14px;
  border: 1px solid rgba(123, 184, 255, 0.14);
  border-radius: 14px;
  background: rgba(10, 18, 36, 0.86);
  color: #dff0ff;
  cursor: pointer;
  transition: border-color 0.2s ease, transform 0.2s ease;
}

.toolbar-button:hover {
  transform: translateY(-1px);
  border-color: rgba(123, 201, 255, 0.24);
}

.toolbar-button.primary {
  border-color: rgba(109, 191, 255, 0.22);
  background: linear-gradient(135deg, rgba(24, 102, 222, 0.92), rgba(42, 190, 255, 0.88));
  box-shadow: 0 14px 28px rgba(22, 90, 198, 0.24);
}

.session-list {
  min-height: 0;
  display: flex;
  flex: 1;
  flex-direction: column;
  gap: 12px;
  overflow: auto;
  padding-right: 4px;
}

.session-list::-webkit-scrollbar {
  width: 8px;
}

.session-list::-webkit-scrollbar-thumb {
  border-radius: 999px;
  background: rgba(112, 188, 255, 0.26);
}

.session-empty {
  min-height: 160px;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  border: 1px dashed rgba(110, 189, 255, 0.18);
  border-radius: 20px;
  padding: 20px;
  color: rgba(214, 231, 255, 0.66);
  text-align: center;
  line-height: 1.8;
}

.session-empty-title {
  color: #eef7ff;
  font-weight: 700;
}

.session-empty-copy {
  margin-top: 6px;
}

.session-item {
  display: grid;
  grid-template-columns: minmax(0, 1fr) auto;
  gap: 12px;
  border: 1px solid rgba(123, 184, 255, 0.1);
  border-radius: 22px;
  background: rgba(9, 18, 36, 0.78);
  transition: border-color 0.2s ease, transform 0.2s ease, box-shadow 0.2s ease;
}

.session-item:hover {
  transform: translateY(-1px);
  border-color: rgba(123, 201, 255, 0.22);
}

.session-item.selected {
  border-color: rgba(82, 177, 255, 0.42);
  box-shadow:
    0 18px 36px rgba(18, 70, 156, 0.2),
    inset 0 0 0 1px rgba(144, 214, 255, 0.08);
}

.session-main {
  min-width: 0;
  padding: 14px 16px;
  border: none;
  border-radius: 22px;
  background: transparent;
  color: inherit;
  cursor: pointer;
  text-align: left;
}

.session-title-row {
  display: flex;
  align-items: center;
  gap: 8px;
}

.session-name {
  min-width: 0;
  font-size: 15px;
  font-weight: 700;
  color: #eef7ff;
  line-height: 1.5;
  word-break: break-word;
}

.session-badge {
  flex-shrink: 0;
  padding: 2px 8px;
  border-radius: 999px;
  background: rgba(55, 194, 255, 0.12);
  color: #8fdcff;
  font-size: 11px;
}

.session-badge.auto {
  color: rgba(206, 230, 255, 0.8);
}

.session-preview {
  margin-top: 8px;
  color: rgba(209, 226, 255, 0.66);
  font-size: 13px;
  line-height: 1.68;
  word-break: break-word;
}

.session-meta {
  margin-top: 10px;
  display: flex;
  flex-wrap: wrap;
  gap: 10px;
  color: rgba(194, 219, 255, 0.46);
  font-size: 11px;
  letter-spacing: 0.04em;
}

.session-id {
  max-width: 150px;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

.session-actions {
  display: flex;
  flex-direction: column;
  gap: 8px;
  padding: 14px 14px 14px 0;
}

.session-action {
  height: 34px;
  padding: 0 12px;
  border: 1px solid rgba(118, 195, 255, 0.12);
  border-radius: 12px;
  background: rgba(14, 25, 46, 0.72);
  color: rgba(219, 236, 255, 0.74);
  cursor: pointer;
}

.session-action.danger {
  color: #ff9aa6;
}

.rename-dialog-backdrop {
  position: absolute;
  inset: 0;
  z-index: 5;
  display: flex;
  align-items: center;
  justify-content: center;
  background: rgba(2, 8, 18, 0.62);
  backdrop-filter: blur(8px);
  border-radius: 28px;
}

.rename-dialog {
  width: min(100%, 360px);
  padding: 18px;
  border-radius: 22px;
  border: 1px solid rgba(120, 191, 255, 0.18);
  background: linear-gradient(180deg, rgba(9, 18, 36, 0.96), rgba(5, 12, 24, 0.96));
  box-shadow:
    0 24px 60px rgba(0, 12, 36, 0.42),
    inset 0 0 0 1px rgba(255, 255, 255, 0.03);
}

.rename-dialog-label {
  color: #8ec9ff;
  font-size: 12px;
  letter-spacing: 0.16em;
  text-transform: uppercase;
}

.rename-dialog-title {
  margin-top: 8px;
  color: #eef7ff;
  font-size: 1rem;
  line-height: 1.6;
}

.rename-form {
  margin-top: 16px;
  display: flex;
  flex-direction: column;
  gap: 12px;
}

.rename-input {
  width: 100%;
  height: 44px;
  border: 1px solid rgba(99, 194, 255, 0.32);
  border-radius: 14px;
  background: rgba(6, 14, 28, 0.92);
  color: #eef7ff;
  padding: 0 14px;
  outline: none;
}

.rename-dialog-actions {
  display: flex;
  gap: 10px;
}

.rename-action {
  height: 38px;
  padding: 0 14px;
  border: 1px solid rgba(118, 195, 255, 0.16);
  border-radius: 12px;
  background: rgba(14, 25, 46, 0.72);
  color: rgba(219, 236, 255, 0.82);
  cursor: pointer;
}

.rename-action.primary {
  background: linear-gradient(135deg, rgba(24, 102, 222, 0.92), rgba(42, 190, 255, 0.88));
  border-color: rgba(109, 191, 255, 0.22);
  color: #fff;
}

@media (max-width: 768px) {
  .mode-panel,
  .session-panel {
    padding: 16px;
  }

  .session-toolbar {
    grid-template-columns: 1fr;
  }

  .toolbar-button,
  .toolbar-button.primary {
    width: 100%;
  }

  .session-item {
    grid-template-columns: 1fr;
  }

  .session-actions {
    flex-direction: row;
    justify-content: flex-end;
    padding: 0 14px 14px;
  }

  .rename-dialog {
    width: 100%;
  }
}
</style>
