package com.qingluo.writeaiagent.model.response;

import com.qingluo.writeaiagent.model.session.NovelSessionMode;

import java.time.Instant;

public record ChatSessionSummaryResponse(
        String chatId,
        NovelSessionMode mode,
        String title,
        String autoGeneratedTitle,
        boolean userRenamed,
        Instant createdAt,
        Instant updatedAt,
        String preview
) {
}
