package com.qingluo.writeaiagent.model.session;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.Instant;

@Data
@NoArgsConstructor
@AllArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class ChatSessionMetadata {

    private String chatId;

    private NovelSessionMode mode;

    private String title;

    private String autoGeneratedTitle;

    private boolean userRenamed;

    private Instant createdAt;

    private Instant updatedAt;

    private String lastPreview;
}
